export interface CountryListEntry {
  slug: string;
  iso2: string;
  iso3: string;
}

/** Countries this pipeline manages. Extend this list to grow past 23 toward the PRD's 100. */
export const countryList: CountryListEntry[] = [
  { slug: "iceland", iso2: "IS", iso3: "ISL" },
  { slug: "south-korea", iso2: "KR", iso3: "KOR" },
  { slug: "japan", iso2: "JP", iso3: "JPN" },
  { slug: "united-states", iso2: "US", iso3: "USA" },
  { slug: "united-kingdom", iso2: "GB", iso3: "GBR" },
  { slug: "france", iso2: "FR", iso3: "FRA" },
  { slug: "germany", iso2: "DE", iso3: "DEU" },
  { slug: "italy", iso2: "IT", iso3: "ITA" },
  { slug: "spain", iso2: "ES", iso3: "ESP" },
  { slug: "china", iso2: "CN", iso3: "CHN" },
  { slug: "india", iso2: "IN", iso3: "IND" },
  { slug: "thailand", iso2: "TH", iso3: "THA" },
  { slug: "vietnam", iso2: "VN", iso3: "VNM" },
  { slug: "australia", iso2: "AU", iso3: "AUS" },
  { slug: "canada", iso2: "CA", iso3: "CAN" },
  { slug: "mexico", iso2: "MX", iso3: "MEX" },
  { slug: "brazil", iso2: "BR", iso3: "BRA" },
  { slug: "egypt", iso2: "EG", iso3: "EGY" },
  { slug: "turkey", iso2: "TR", iso3: "TUR" },
  { slug: "indonesia", iso2: "ID", iso3: "IDN" },
  { slug: "philippines", iso2: "PH", iso3: "PHL" },
  { slug: "switzerland", iso2: "CH", iso3: "CHE" },
  { slug: "netherlands", iso2: "NL", iso3: "NLD" },
  // Added to cover the top 50 countries by international tourist arrivals, plus North Korea.
  { slug: "greece", iso2: "GR", iso3: "GRC" },
  { slug: "austria", iso2: "AT", iso3: "AUT" },
  { slug: "united-arab-emirates", iso2: "AE", iso3: "ARE" },
  { slug: "saudi-arabia", iso2: "SA", iso3: "SAU" },
  { slug: "portugal", iso2: "PT", iso3: "PRT" },
  { slug: "malaysia", iso2: "MY", iso3: "MYS" },
  { slug: "poland", iso2: "PL", iso3: "POL" },
  { slug: "morocco", iso2: "MA", iso3: "MAR" },
  { slug: "hungary", iso2: "HU", iso3: "HUN" },
  { slug: "albania", iso2: "AL", iso3: "ALB" },
  { slug: "tunisia", iso2: "TN", iso3: "TUN" },
  { slug: "peru", iso2: "PE", iso3: "PER" },
  { slug: "dominican-republic", iso2: "DO", iso3: "DOM" },
  { slug: "sweden", iso2: "SE", iso3: "SWE" },
  { slug: "argentina", iso2: "AR", iso3: "ARG" },
  { slug: "uzbekistan", iso2: "UZ", iso3: "UZB" },
  { slug: "ireland", iso2: "IE", iso3: "IRL" },
  { slug: "iran", iso2: "IR", iso3: "IRN" },
  { slug: "colombia", iso2: "CO", iso3: "COL" },
  { slug: "bahrain", iso2: "BH", iso3: "BHR" },
  { slug: "cambodia", iso2: "KH", iso3: "KHM" },
  { slug: "jordan", iso2: "JO", iso3: "JOR" },
  { slug: "georgia", iso2: "GE", iso3: "GEO" },
  { slug: "qatar", iso2: "QA", iso3: "QAT" },
  { slug: "andorra", iso2: "AD", iso3: "AND" },
  { slug: "cyprus", iso2: "CY", iso3: "CYP" },
  { slug: "uruguay", iso2: "UY", iso3: "URY" },
  { slug: "chile", iso2: "CL", iso3: "CHL" },
  { slug: "north-korea", iso2: "KP", iso3: "PRK" },
];
